config/routes.rb
TransactionTracker::Application.routes.draw do
  resources :transactions, :only => [:index, :show, :new, :create, :edit, :update]

  get '/current_month_transactions',
    :to => "transactions#current_month_transactions",
    :as => "current_month_transactions"

  root :to => "transactions#index"
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :name, :store, :category, :price

  validates :name, :presence => true
  validates :category, :presence => true
  validates :price, :presence => true

  def initialize(attr={})
    super(attr)
    self.day = Date.today
  end

  def to_s
    "#{self.name}-#{self.category}"
  end
end

#      Transaction.all(:group => "category").collect do |c| 
#      [c.category, Transaction.sum("price", :conditions => "category='#{c.category}'")]

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :find_transaction, :only => [:show, :edit, 
                                             :update]

  def index
    @transactions = Transaction.all
  end
    
  def show; end

  def new
    @transaction = Transaction.new
  end

  def create
    if created?
      flash[:success] = "Created a new Transaction."
      redirect_to @transaction
    else
      flash.now[:error] = "Invalid Transaction information."
      render :action => :new
    end 
  end

  def edit; end

  def update
    if updated? 
      flash[:success] = "Transaction updated."
      redirect_to @transaction
    else
      flash.now[:error] = "Invalid information!"
      render :action => :edit
    end
  end

  def current_month_transactions
    @transactions = CurrentMonthTransactions.get_transactions
    render :action => :index
  end

  private

    def find_transaction
      @transaction = Transaction.find(params[:id])
    end

    def created?
      attributes = DowncaseCategory.downcase(params[:transaction])
      @transaction = Transaction.new(attributes)
      @transaction.save
    end

    def updated?
      attributes = DowncaseCategory.downcase(params[:transaction])
      @transaction.update_attributes(attributes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
    image_tag("tracker_logo.png", :size => "350x100", :alt => "Transaction Tracker", :class => "round")
  end
end

app/helpers/transaction_helper.rb
module TransactionHelper
  def draw_payment_per_category_chart(transactions)
    ChartGenerator.draw(transactions)
    image_tag("payment_per_category.png", :size => "400x400", :alt => "Payment Per Category", :class => "round")
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
				<li><%= link_to "About", "#" %></li>
				<li><%= link_to "Contact", "#" %></li>
        <li><a href="http://masihjesus.wordpress.com" target=_blank>Blog</a></li>
		</ul>
	</nav>
</footer>	

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, transactions_path %>
  <nav class="round">
    <ul>
        <li><%= link_to "Transactions", transactions_path %></li>
        <li><%= link_to "Current Month", current_month_transactions_path %></li>
        <li><%= link_to "Home", transactions_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transaction Tracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %></br>
    <section class="round">
      <% flash.each do |key, value| %>
        <div class="<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </section>
    <%= render 'layouts/footer' %><br />
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/transactions/_transaction_form.html.erb
<%= form_for(@transaction) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :store %><br />
    <%= f.text_field :store %>
  </div>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<%= render "transaction_form" %>

app/views/transactions/index.html.erb
<table summary="list of transactions">
  <tr>
    <td>
      <%= link_to "New Transaction", new_transaction_path %>
      <ul class="all-transactions">
        <% @transactions.each do |transaction| %>
          <li class="transaction">
          <%= link_to transaction, transaction_path(transaction) %>
          </li>
        <% end %>
      </ul>
    </td>
    <td class="chart">
      <% if !@transactions.nil? && !@transactions.empty? %>
        <%= draw_payment_per_category_chart(@transactions) %>
      <% end %>
    </td>
  </tr>
</table>

app/views/transactions/new.html.erb
<%= form_for(@transaction) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :store %><br />
    <%= f.text_field :store %>
  </div>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/show.html.erb
<%= link_to "Edit Transaction", edit_transaction_path(@transaction) %>

<h1>Transaction</h1>

<ul>
  <li><h3><%= @transaction.name %></h3></li> 
  <li><h3><%= @transaction.store %></h3></li> 
  <li><h3><%= @transaction.category %></h3></li> 
  <li><h3><%= @transaction.price %></h3></li> 
</ul>